// Code generated by nbtgen. DO NOT EDIT.

package main

import (
	"os"

	"gitlab.com/kyle_anderson/nbt/pkg/nbt"
	"gitlab.com/kyle_anderson/nbt/pkg/ntr"
	ntrmain "gitlab.com/kyle_anderson/nbt/pkg/ntr/main"
)

func getNamedTasks() map[string]ntr.TaskSupplier {
	result := make(map[string]ntr.TaskSupplier)
	result["LinkProgram"] = func(arg string) (t nbt.Task, err error) {
		t = NewTaskLinkProgram()
		return
	}
	return result
}
func main() {
	ntrmain.Run(getNamedTasks(), os.Args[1:])
}
